### ISSUE TITLE
OS-Climate SSL Certificates 

### ISSUE THREAD

**Issue by AndNeg88** [os-climate/ITR#188] opened 2023-05-08 10:24 UTC
git pull
fatal: unable to access 'https://github.com/os-climate/ITR.git/': SSL certificate problem: unable to get local issuer certificate

**Comment by MichaelTiemannOSC** [comment] 2023-05-08 17:03
Applied workaround from this for now: https://github.com/desktop/desktop/issues/9293

**Comment by MightyNerdEric** [comment] 2023-05-09 17:15
This is an issue with @AndNeg88's connection to Github. The root cause is likely a VPN, proxy, firewall, or similar connection midpoint. But to be clear, there are no "os-climate ssl certificates" involved in a connection between a user's PC and Github. Only Github SSL.

@MichaelTiemannOSC mentioned during our meeting yesterday that this was previously working, and the error came up suddenly. I'm guessing @AndNeg88 is trying to connect on a new network or VPN. If so, configuration may need to be adjusted there. If not, it could be an issue with the local certificate store.

Since this is *not* an issue with ITR, I'm going to close this issue. https://github.com/desktop/desktop might be a more appropriate place to look for help with Github Desktop issues.

**Closed by MightyNerdEric** 2023-05-09 17:15 UTC
Labels: question
